micronaut:
  application:
    name: mnFundingJdbcDemo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
vertx:
  mysql:
    client:
      port: 3306
      host: the-host
      database: the-db
      user: user
      password: password
      maxSize: 5
netty:
  default:
    allocator:
      max-order: 3
