micronaut:
  application:
    name: mnFundingJdbcDemo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:mysql://localhost:3306/mn-funding
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: "secret"
    schema-generate: NONE
    dialect: MYSQL
liquibase:
  datasources:
    default:
      enabled: true
      change-log: "classpath:db/liquibase-changelog.xml"
      drop-first: true
# vertx:
#   mysql:
#     client:
#       port: 3306
#       host: the-host
#       database: the-db
#       user: user
#       password: password
#       maxSize: 5
# netty:
#   default:
#     allocator:
#       max-order: 3
